import React, { Component } from "react";
import Send from "../send";
import Select from "react-select";
import {
  MDBCard,
  MDBCardBody,
  MDBRow,
  MDBCol,
  MDBIcon,
  MDBCardText,
  MDBBadge,
} from "mdbreact";

class AxiosTestPage extends Component {
  constructor(props) {
    super(props);
    this.state = {
      display: {
        data: [
          [
            {
              columnName: "status_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "19",
            },
            {
              columnName: "company_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "3",
            },
            {
              columnName: "contract_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "853",
            },
            {
              columnName: "company_name",
              inputType: "select",
              label: "Company",
              updatedValue: null,
              value: "The Stageline Company, LLC",
            },
            {
              columnName: "status_value",
              inputType: "select",
              label: "Contract Status",
              updatedValue: null,
              value: "Active",
            },
            {
              columnName: "facility_name",
              inputType: "select",
              label: "Administration Office",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_type_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "2",
            },
            {
              columnName: "end_contract_date",
              inputType: "date",
              label: "End Contract Term",
              updatedValue: null,
              value: "2020-01-03",
            },
            {
              columnName: "solicitation_date",
              inputType: "date",
              label: "Date of Solicitation",
              updatedValue: "2020-1-9",
              value: "2020-1-9",
            },
            {
              columnName: "contract_type_code",
              inputType: "text",
              label: "Contract Type Code",
              updatedValue: null,
              value: "DRO",
            },
            {
              columnName: "begin_contract_date",
              inputType: "date",
              label: "Begin Contract Term",
              updatedValue: null,
              value: "2020-01-10",
            },
            {
              columnName: "solicitation_number",
              inputType: "text",
              label: "Solicitation No.",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "3",
            },
            {
              columnName: "end_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_code",
              inputType: "text",
              label: "Division",
              updatedValue: null,
              value: "CDS",
            },
            {
              columnName: "custom_end_destination",
              inputType: "text",
              label: "End City",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "external_contract_code",
              inputType: "text",
              label: "Contract No.",
              updatedValue: null,
              value: "Test006",
            },
            {
              columnName: "start_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "custom_start_destination",
              inputType: "text",
              label: "Start City",
              updatedValue: null,
              value: "",
            },
          ],
          [
            {
              columnName: "status_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "19",
            },
            {
              columnName: "company_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "3",
            },
            {
              columnName: "contract_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "853",
            },
            {
              columnName: "company_name",
              inputType: "select",
              label: "Company",
              updatedValue: null,
              value: "The Stageline Company, LLC",
            },
            {
              columnName: "status_value",
              inputType: "select",
              label: "Contract Status",
              updatedValue: null,
              value: "Active",
            },
            {
              columnName: "facility_name",
              inputType: "select",
              label: "Administration Office",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_type_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "2",
            },
            {
              columnName: "end_contract_date",
              inputType: "date",
              label: "End Contract Term",
              updatedValue: null,
              value: "2020-01-03",
            },
            {
              columnName: "solicitation_date",
              inputType: "date",
              label: "Date of Solicitation",
              updatedValue: null,
              value: "2020-01-01",
            },
            {
              columnName: "contract_type_code",
              inputType: "text",
              label: "Contract Type Code",
              updatedValue: null,
              value: "DRO",
            },
            {
              columnName: "begin_contract_date",
              inputType: "date",
              label: "Begin Contract Term",
              updatedValue: null,
              value: "2020-01-10",
            },
            {
              columnName: "solicitation_number",
              inputType: "text",
              label: "Solicitation No.",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_id",
              inputType: null,
              label: null,
              updatedValue: "3",
              value: "3",
            },
            {
              columnName: "end_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_code",
              inputType: "text",
              label: "Division",
              updatedValue: "CDS  Contract Delivery Service",
              value: "CDS  Contract Delivery Service",
            },
            {
              columnName: "custom_end_destination",
              inputType: "text",
              label: "End City",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "external_contract_code",
              inputType: "text",
              label: "Contract No.",
              updatedValue: null,
              value: "Test006",
            },
            {
              columnName: "start_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "custom_start_destination",
              inputType: "text",
              label: "Start City",
              updatedValue: null,
              value: "",
            },
          ],
          [
            {
              columnName: "status_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "19",
            },
            {
              columnName: "company_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "3",
            },
            {
              columnName: "contract_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "853",
            },
            {
              columnName: "company_name",
              inputType: "select",
              label: "Company",
              updatedValue: null,
              value: "The Stageline Company, LLC",
            },
            {
              columnName: "status_value",
              inputType: "select",
              label: "Contract Status",
              updatedValue: null,
              value: "Active",
            },
            {
              columnName: "facility_name",
              inputType: "select",
              label: "Administration Office",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_type_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "2",
            },
            {
              columnName: "end_contract_date",
              inputType: "date",
              label: "End Contract Term",
              updatedValue: null,
              value: "2020-01-03",
            },
            {
              columnName: "solicitation_date",
              inputType: "date",
              label: "Date of Solicitation",
              updatedValue: null,
              value: "2020-01-01",
            },
            {
              columnName: "contract_type_code",
              inputType: "text",
              label: "Contract Type Code",
              updatedValue: null,
              value: "DRO",
            },
            {
              columnName: "begin_contract_date",
              inputType: "date",
              label: "Begin Contract Term",
              updatedValue: null,
              value: "2020-01-10",
            },
            {
              columnName: "solicitation_number",
              inputType: "text",
              label: "Solicitation No.",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_id",
              inputType: null,
              label: null,
              updatedValue: "2",
              value: "2",
            },
            {
              columnName: "end_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_code",
              inputType: "text",
              label: "Division",
              updatedValue: "PNT  Postal Network Transportation",
              value: "PNT  Postal Network Transportation",
            },
            {
              columnName: "custom_end_destination",
              inputType: "text",
              label: "End City",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "external_contract_code",
              inputType: "text",
              label: "Contract No.",
              updatedValue: null,
              value: "Test006",
            },
            {
              columnName: "start_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "custom_start_destination",
              inputType: "text",
              label: "Start City",
              updatedValue: null,
              value: "",
            },
          ],
          [
            {
              columnName: "status_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "19",
            },
            {
              columnName: "company_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "3",
            },
            {
              columnName: "contract_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "853",
            },
            {
              columnName: "company_name",
              inputType: "select",
              label: "Company",
              updatedValue: null,
              value: "The Stageline Company, LLC",
            },
            {
              columnName: "status_value",
              inputType: "select",
              label: "Contract Status",
              updatedValue: null,
              value: "Active",
            },
            {
              columnName: "facility_name",
              inputType: "select",
              label: "Administration Office",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_type_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "2",
            },
            {
              columnName: "end_contract_date",
              inputType: "date",
              label: "End Contract Term",
              updatedValue: null,
              value: "2020-01-03",
            },
            {
              columnName: "solicitation_date",
              inputType: "date",
              label: "Date of Solicitation",
              updatedValue: null,
              value: "2020-01-01",
            },
            {
              columnName: "contract_type_code",
              inputType: "text",
              label: "Contract Type Code",
              updatedValue: null,
              value: "DRO",
            },
            {
              columnName: "begin_contract_date",
              inputType: "date",
              label: "Begin Contract Term",
              updatedValue: null,
              value: "2020-01-10",
            },
            {
              columnName: "solicitation_number",
              inputType: "text",
              label: "Solicitation No.",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_id",
              inputType: null,
              label: null,
              updatedValue: "3",
              value: "3",
            },
            {
              columnName: "end_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_code",
              inputType: "text",
              label: "Division",
              updatedValue: "CDS  Contract Delivery Service",
              value: "CDS  Contract Delivery Service",
            },
            {
              columnName: "custom_end_destination",
              inputType: "text",
              label: "End City",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "external_contract_code",
              inputType: "text",
              label: "Contract No.",
              updatedValue: null,
              value: "Test006",
            },
            {
              columnName: "start_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "custom_start_destination",
              inputType: "text",
              label: "Start City",
              updatedValue: null,
              value: "",
            },
          ],
          [
            {
              columnName: "status_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "19",
            },
            {
              columnName: "company_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "3",
            },
            {
              columnName: "contract_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "853",
            },
            {
              columnName: "company_name",
              inputType: "select",
              label: "Company",
              updatedValue: null,
              value: "The Stageline Company, LLC",
            },
            {
              columnName: "status_value",
              inputType: "select",
              label: "Contract Status",
              updatedValue: null,
              value: "Active",
            },
            {
              columnName: "facility_name",
              inputType: "select",
              label: "Administration Office",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_type_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "2",
            },
            {
              columnName: "end_contract_date",
              inputType: "date",
              label: "End Contract Term",
              updatedValue: null,
              value: "2020-01-03",
            },
            {
              columnName: "solicitation_date",
              inputType: "date",
              label: "Date of Solicitation",
              updatedValue: null,
              value: "2020-01-01",
            },
            {
              columnName: "contract_type_code",
              inputType: "text",
              label: "Contract Type Code",
              updatedValue: null,
              value: "DRO",
            },
            {
              columnName: "begin_contract_date",
              inputType: "date",
              label: "Begin Contract Term",
              updatedValue: null,
              value: "2020-01-10",
            },
            {
              columnName: "solicitation_number",
              inputType: "text",
              label: "Solicitation No.",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_id",
              inputType: null,
              label: null,
              updatedValue: "1",
              value: "1",
            },
            {
              columnName: "end_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_code",
              inputType: "text",
              label: "Division",
              updatedValue: "LDT  Local Distribution Transportation",
              value: "LDT  Local Distribution Transportation",
            },
            {
              columnName: "custom_end_destination",
              inputType: "text",
              label: "End City",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "external_contract_code",
              inputType: "text",
              label: "Contract No.",
              updatedValue: null,
              value: "Test006",
            },
            {
              columnName: "start_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "custom_start_destination",
              inputType: "text",
              label: "Start City",
              updatedValue: null,
              value: "",
            },
          ],
          [
            {
              columnName: "status_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "19",
            },
            {
              columnName: "company_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "3",
            },
            {
              columnName: "contract_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "853",
            },
            {
              columnName: "company_name",
              inputType: "select",
              label: "Company",
              updatedValue: null,
              value: "The Stageline Company, LLC",
            },
            {
              columnName: "status_value",
              inputType: "select",
              label: "Contract Status",
              updatedValue: null,
              value: "Active",
            },
            {
              columnName: "facility_name",
              inputType: "select",
              label: "Administration Office",
              updatedValue: null,
              value: "FOREST HILL",
            },
            {
              columnName: "contract_type_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "2",
            },
            {
              columnName: "end_contract_date",
              inputType: "date",
              label: "End Contract Term",
              updatedValue: null,
              value: "2020-01-03",
            },
            {
              columnName: "solicitation_date",
              inputType: "date",
              label: "Date of Solicitation",
              updatedValue: null,
              value: "2020-01-01",
            },
            {
              columnName: "contract_type_code",
              inputType: "text",
              label: "Contract Type Code",
              updatedValue: null,
              value: "DRO",
            },
            {
              columnName: "begin_contract_date",
              inputType: "date",
              label: "Begin Contract Term",
              updatedValue: null,
              value: "2020-01-10",
            },
            {
              columnName: "solicitation_number",
              inputType: "text",
              label: "Solicitation No.",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_id",
              inputType: null,
              label: null,
              updatedValue: "3",
              value: "3",
            },
            {
              columnName: "end_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_code",
              inputType: "text",
              label: "Division",
              updatedValue: "CDS  Contract Delivery Service",
              value: "CDS  Contract Delivery Service",
            },
            {
              columnName: "custom_end_destination",
              inputType: "text",
              label: "End City",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "external_contract_code",
              inputType: "text",
              label: "Contract No.",
              updatedValue: null,
              value: "Test006",
            },
            {
              columnName: "start_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "custom_start_destination",
              inputType: "text",
              label: "Start City",
              updatedValue: null,
              value: "",
            },
          ],
          [
            {
              columnName: "status_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "19",
            },
            {
              columnName: "company_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "3",
            },
            {
              columnName: "contract_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "853",
            },
            {
              columnName: "company_name",
              inputType: "select",
              label: "Company",
              updatedValue: null,
              value: "The Stageline Company, LLC",
            },
            {
              columnName: "status_value",
              inputType: "select",
              label: "Contract Status",
              updatedValue: null,
              value: "Active",
            },
            {
              columnName: "facility_name",
              inputType: "select",
              label: "Administration Office",
              updatedValue: "21050  FOREST HILL",
              value: "21050  FOREST HILL",
            },
            {
              columnName: "contract_type_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "2",
            },
            {
              columnName: "end_contract_date",
              inputType: "date",
              label: "End Contract Term",
              updatedValue: null,
              value: "2020-01-03",
            },
            {
              columnName: "solicitation_date",
              inputType: "date",
              label: "Date of Solicitation",
              updatedValue: null,
              value: "2020-01-01",
            },
            {
              columnName: "contract_type_code",
              inputType: "text",
              label: "Contract Type Code",
              updatedValue: null,
              value: "DRO",
            },
            {
              columnName: "begin_contract_date",
              inputType: "date",
              label: "Begin Contract Term",
              updatedValue: null,
              value: "2020-01-10",
            },
            {
              columnName: "solicitation_number",
              inputType: "text",
              label: "Solicitation No.",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "2",
            },
            {
              columnName: "end_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_code",
              inputType: "text",
              label: "Division",
              updatedValue: null,
              value: "PNT",
            },
            {
              columnName: "custom_end_destination",
              inputType: "text",
              label: "End City",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "external_contract_code",
              inputType: "text",
              label: "Contract No.",
              updatedValue: null,
              value: "Test006",
            },
            {
              columnName: "start_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "custom_start_destination",
              inputType: "text",
              label: "Start City",
              updatedValue: null,
              value: "",
            },
          ],
          [
            {
              columnName: "status_id",
              inputType: null,
              label: null,
              updatedValue: "19",
              value: "19",
            },
            {
              columnName: "company_id",
              inputType: null,
              label: null,
              updatedValue: "3",
              value: "3",
            },
            {
              columnName: "contract_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "company_name",
              inputType: "select",
              label: "Company",
              updatedValue: "The Stageline Company, LLC",
              value: "The Stageline Company, LLC",
            },
            {
              columnName: "status_value",
              inputType: "select",
              label: "Contract Status",
              updatedValue: "Active",
              value: "Active",
            },
            {
              columnName: "facility_name",
              inputType: "select",
              label: "Administration Office",
              updatedValue: "60107  STREAMWOOD",
              value: "60107  STREAMWOOD",
            },
            {
              columnName: "contract_type_id",
              inputType: null,
              label: null,
              updatedValue: "2",
              value: "2",
            },
            {
              columnName: "end_contract_date",
              inputType: "date",
              label: "End Contract Term",
              updatedValue: "2020-1-3",
              value: "2020-1-3",
            },
            {
              columnName: "solicitation_date",
              inputType: "date",
              label: "Date of Solicitation",
              updatedValue: null,
              value: "2020-01-01",
            },
            {
              columnName: "contract_type_code",
              inputType: "text",
              label: "Contract Type Code",
              updatedValue: "DRO  Dynamic Routing Optimization",
              value: "DRO  Dynamic Routing Optimization",
            },
            {
              columnName: "begin_contract_date",
              inputType: "date",
              label: "Begin Contract Term",
              updatedValue: null,
              value: "2020-01-10",
            },
            {
              columnName: "solicitation_number",
              inputType: "text",
              label: "Solicitation No.",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_id",
              inputType: null,
              label: null,
              updatedValue: "2",
              value: "2",
            },
            {
              columnName: "end_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "contract_division_code",
              inputType: "text",
              label: "Division",
              updatedValue: "PNT  ",
              value: "PNT  ",
            },
            {
              columnName: "custom_end_destination",
              inputType: "text",
              label: "End City",
              updatedValue: null,
              value: "",
            },
            {
              columnName: "external_contract_code",
              inputType: "text",
              label: "Contract No.",
              updatedValue: "Test006",
              value: "Test006",
            },
            {
              columnName: "start_state_province_id",
              inputType: null,
              label: null,
              updatedValue: null,
              value: "",
            },
            {
              columnName: "custom_start_destination",
              inputType: "text",
              label: "Start City",
              updatedValue: null,
              value: "",
            },
          ],
        ],
        our_session: {
          IDSession: "139",
          NavPermissions: [
            ["/bids", "Write", "Dashboard", 1],
            ["/ticketcreate", "Write", "Create Ticket", 2],
            ["/tickethistory", "Write", "Ticket History", 3],
            ["/ticketapproval", "Write", "Awaiting Approval", 4],
            ["/ticketmod", "Write", "Edit Ticket", 5],
            ["/ticketclose", "Write", "Close Ticket", 6],
            ["/bids#edit", "Write", "Edit Contract", 7],
            ["/bids#create", "Write", "Create Contract", 8],
            ["/contracts", "Write", "Dashboard", 9],
            ["/contracts", "Write", "Dashboard", 9],
          ],
          SessionID: "z5VTYifaGwfUxvqv6gLFHm72Z8_l4WRA",
          match: true,
        },
      },
    };
  }

  // componentDidMount() {
  //   Send.get("/contract/History/853", this.props, "").then((res) => {
  //     var obj = res.data[0][0].columnName;
  //     console.log();

  //     this.setState({ display: res.data[0][0] });
  //   });
  // }

  render() {
    return (
      <React.Fragment>
        <MDBRow className="mb-4">
          <MDBCol xl="12" md="12" className="mb-r">
            <MDBCard className="cascading-admin-card">
              <div className="admin-up">
                <MDBIcon icon="file-invoice-dollar" className="primary-color" />
                <div className="data">
                  <MDBCardText>Endpoint / Axios Test Page</MDBCardText>
                  <h4>
                    <MDBBadge color="primary-color" pill></MDBBadge>
                  </h4>
                </div>
              </div>

              <MDBCardBody>
                <h2 className="m-3 ">Endpoint / Axios Test Page</h2>
              </MDBCardBody>
            </MDBCard>
          </MDBCol>
        </MDBRow>
        <div>Current Active Contracts: &nbsp;</div>
        {this.state.display.data.map((content, index) => {
          return <div>{content.label}</div>;
        })}
      </React.Fragment>
    );
  }
}
export default AxiosTestPage;
